spring.application.name=jnvst-guru-backend

server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/jnvst_guru_backend}
spring.datasource.username=${DB_USERNAME:jnvst_guru}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
