ALTER TABLE IF EXISTS application.mat_questions
    RENAME TO mat_questions_legacy;

CREATE TABLE application.mat_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE application.mat_topic_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL REFERENCES application.mat_topics(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (topic_id, language_code)
);

CREATE TABLE application.mat_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL REFERENCES application.mat_topics(id),
    question_image_url TEXT NOT NULL,
    option_a_image_url TEXT NOT NULL,
    option_b_image_url TEXT NOT NULL,
    option_c_image_url TEXT NOT NULL,
    option_d_image_url TEXT NOT NULL,
    correct_option VARCHAR(1) NOT NULL CHECK (correct_option IN ('A', 'B', 'C', 'D')),
    difficulty VARCHAR(30),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (sort_order IS NULL OR sort_order >= 0)
);

CREATE INDEX idx_mat_questions_topic_active_order
    ON application.mat_questions (topic_id, is_active, sort_order, id);
CREATE INDEX idx_mat_topics_active_order
    ON application.mat_topics (is_active, sort_order, id);

CREATE TRIGGER trg_mat_topics_set_updated_at
BEFORE UPDATE ON application.mat_topics
FOR EACH ROW EXECUTE FUNCTION application.set_updated_at();
CREATE TRIGGER trg_mat_topic_translations_set_updated_at
BEFORE UPDATE ON application.mat_topic_translations
FOR EACH ROW EXECUTE FUNCTION application.set_updated_at();
CREATE TRIGGER trg_mat_questions_set_updated_at
BEFORE UPDATE ON application.mat_questions
FOR EACH ROW EXECUTE FUNCTION application.set_updated_at();

INSERT INTO application.mat_topics (code, sort_order)
VALUES
    ('ODD_ONE_OUT', 1), ('FIGURE_MATCHING', 2), ('FIGURE_COMPLETION', 3),
    ('FIGURE_SERIES', 4), ('FIGURE_ANALOGY', 5),
    ('GEOMETRICAL_FIGURE_COMPLETION', 6), ('MIRROR_IMAGE', 7),
    ('PAPER_FOLDING_PUNCHING', 8), ('CUT_OUT_FORMATION', 9),
    ('EMBEDDED_FIGURES', 10)
ON CONFLICT (code) DO NOTHING;

INSERT INTO application.mat_topic_translations (topic_id, language_code, name, description)
SELECT t.id, s.language_code, s.name, s.description
FROM (VALUES
    ('ODD_ONE_OUT', 'en', 'Odd One Out', 'Identify the figure that does not belong to the group.'),
    ('FIGURE_MATCHING', 'en', 'Figure Matching', 'Select the option that matches the given figure.'),
    ('FIGURE_COMPLETION', 'en', 'Figure Completion', 'Choose the figure that completes the pattern.'),
    ('FIGURE_SERIES', 'en', 'Figure Series', 'Find the next figure in the visual series.'),
    ('FIGURE_ANALOGY', 'en', 'Analogy / Figure Relationship', 'Identify the figure relationship and its matching option.'),
    ('GEOMETRICAL_FIGURE_COMPLETION', 'en', 'Geometrical Figure Completion', 'Complete the geometrical figure using the correct option.'),
    ('MIRROR_IMAGE', 'en', 'Mirror Image', 'Choose the correct mirror image of the given figure.'),
    ('PAPER_FOLDING_PUNCHING', 'en', 'Paper Folding / Punching', 'Visualize folds and punched holes in the paper.'),
    ('CUT_OUT_FORMATION', 'en', 'Cut-out Pieces / Formation', 'Select the figure formed from the given cut-out pieces.'),
    ('EMBEDDED_FIGURES', 'en', 'Embedded Figures', 'Locate the given figure within a larger figure.'),
    ('ODD_ONE_OUT', 'bn', 'বেমানান চিত্র', 'দলের সঙ্গে মেলে না এমন চিত্রটি শনাক্ত করুন।'),
    ('FIGURE_MATCHING', 'bn', 'চিত্র মেলানো', 'প্রদত্ত চিত্রের সঙ্গে মেলে এমন বিকল্পটি বেছে নিন।'),
    ('FIGURE_COMPLETION', 'bn', 'চিত্র সম্পূর্ণকরণ', 'নকশাটি সম্পূর্ণ করে এমন চিত্রটি বেছে নিন।'),
    ('FIGURE_SERIES', 'bn', 'চিত্রের ধারা', 'চিত্রের ধারায় পরবর্তী চিত্রটি খুঁজে বের করুন।'),
    ('FIGURE_ANALOGY', 'bn', 'সাদৃশ্য / চিত্রের সম্পর্ক', 'চিত্রের সম্পর্ক বুঝে সঠিক বিকল্পটি বেছে নিন।'),
    ('GEOMETRICAL_FIGURE_COMPLETION', 'bn', 'জ্যামিতিক চিত্র সম্পূর্ণকরণ', 'সঠিক বিকল্প দিয়ে জ্যামিতিক চিত্রটি সম্পূর্ণ করুন।'),
    ('MIRROR_IMAGE', 'bn', 'আয়না প্রতিবিম্ব', 'প্রদত্ত চিত্রের সঠিক আয়না প্রতিবিম্বটি বেছে নিন।'),
    ('PAPER_FOLDING_PUNCHING', 'bn', 'কাগজ ভাঁজ / ছিদ্র করা', 'কাগজ ভাঁজ ও ছিদ্র করার ফলাফল কল্পনা করুন।'),
    ('CUT_OUT_FORMATION', 'bn', 'কাটা অংশ / গঠন', 'কাটা অংশগুলি দিয়ে তৈরি সঠিক চিত্রটি বেছে নিন।'),
    ('EMBEDDED_FIGURES', 'bn', 'অন্তর্নিহিত চিত্র', 'বড় চিত্রের মধ্যে দেওয়া চিত্রটি খুঁজে বের করুন।')
) AS s(code, language_code, name, description)
JOIN application.mat_topics t ON t.code = s.code
ON CONFLICT (topic_id, language_code) DO NOTHING;
