CREATE TABLE application.mat_question_explanations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mat_question_id BIGINT NOT NULL REFERENCES application.mat_questions(id) ON DELETE CASCADE,
    language_code VARCHAR(10) NOT NULL,
    explanation TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (mat_question_id, language_code)
);

CREATE INDEX idx_mat_question_explanations_language_question
    ON application.mat_question_explanations (language_code, mat_question_id);
