ALTER TABLE application.language_questions
    RENAME TO language_questions_legacy_shared;

ALTER TABLE application.language_passages_english
    RENAME TO language_passages_english_legacy;
ALTER TABLE application.language_passages_hindi
    RENAME TO language_passages_hindi_legacy;
ALTER TABLE application.language_passages_bengali
    RENAME TO language_passages_bengali_legacy;

ALTER TABLE application.language_question_english
    RENAME TO language_question_english_legacy;
ALTER TABLE application.language_question_hindi
    RENAME TO language_question_hindi_legacy;
ALTER TABLE application.language_question_bengali
    RENAME TO language_question_bengali_legacy;

CREATE TABLE application.language_passages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code VARCHAR(10) NOT NULL CHECK (language_code IN ('en', 'hi', 'bn')),
    batch_no VARCHAR(60) NOT NULL,
    passage_number INTEGER NOT NULL CHECK (passage_number BETWEEN 1 AND 4),
    passage_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (language_code, batch_no, passage_number),
    UNIQUE (id, language_code, batch_no)
);

CREATE INDEX idx_language_passages_batch_order
    ON application.language_passages (language_code, batch_no, passage_number, id);

CREATE TABLE application.language_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code VARCHAR(10) NOT NULL CHECK (language_code IN ('en', 'hi', 'bn')),
    batch_no VARCHAR(60) NOT NULL,
    passage_id BIGINT NOT NULL REFERENCES application.language_passages(id),
    question_number INTEGER NOT NULL CHECK (question_number BETWEEN 1 AND 20),
    question_text TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option VARCHAR(1) NOT NULL CHECK (correct_option IN ('A', 'B', 'C', 'D')),
    difficulty VARCHAR(30) NOT NULL,
    explanation TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (language_code, batch_no, question_number),
    UNIQUE (id, language_code, batch_no),
    CONSTRAINT fk_language_questions_passage_language_batch
        FOREIGN KEY (passage_id, language_code, batch_no)
        REFERENCES application.language_passages(id, language_code, batch_no)
);

CREATE INDEX idx_language_questions_practice_order
    ON application.language_questions (language_code, batch_no, is_active, difficulty, question_number, id);
